### ISSUE TITLE
Compiling fails

### ISSUE THREAD

**Issue by MrBollie** [onkelDead/tascam-gtk#1]
Hi there,
tried compiling on ARCH linux by using 
./configure
make
Ended up with:
make[1]: *** No rule to make target 'de.paraair.tascamgtk.gschema.xml', needed by 'de.paraair.tascamgtk.gschema.valid'.  Stop.

Am I missing something?

Cheers
Bollie

**Comment by onkelDead** [comment]
Hi,
...oups, seems I've missed something.
I assume that file was missed during last commit, but I'll check it on a clean system and will get back to you.

Greets,
Detlef

**Comment by MrBollie** [comment]
Build now works. :)

Dankeschön!
