### ISSUE TITLE
äh do the output configs get sent to the tascam aswell when loading a configuration? i find that to not be the case.

### ISSUE THREAD

**Issue by MparkG** [onkelDead/tascam-gtk#14]
"äh do the output configs get sent to the tascam aswell when loading a configuration? i find that to not be the case."

... for me it doesnt seem to set the outputs, e.g. ch1, ch2 to the mixer outputs, ch{3,5,7},ch{4,6,8} to computer output 1 and 2

also the button "computer out to stereo bus doesnt seem to be disabled when loading the configuration.
I dont know if checks are implemented to only send the edited (from default) options, but the default options in this application dont seem to cohere with the default options in my tascam..

also my view looks like this;
![image](https://user-images.githubusercontent.com/26872340/98998996-48382480-2537-11eb-9362-9af32d585a46.png)

with whichever theme or style of gtk i try, i cant get to see the scale to the right of the volume sliders and the colorful meter bars dont always show up.

If there is any help available, thatd be nice.
Thanks and kind regards,
Park

**Comment by onkelDead** [comment]
Hi,
just made a quick check if config load is send to device. to me it works.
Regarding app-defaults, seems you are right, application defaults differs from power-on defaults esp. bus out button.
As an alsa based mixer, its settings are also stored at /var/lib/alsa/asound.state
Reg. theme I'll investigate deeper later, scales are missing on mine also.

BTW. I personaly do not make use of it anymore, since I own another multi-channel device.

**Comment by MparkG** [comment]
Hello uncledead,
Indeed, it seems the tascam doesnt really work reliably over the length of usb cable i have.
With a 1m one it does send the output configuration when loading stored settings.
I guess one could improve the reliability of the transfer by slowing the it down? 

the settings at  /var/lib/alsa/asound.state dont exist for me (on manjaro)
the whole /var/lib/alsa folder appears empty.

I can understand you may not have interest or time to modify this program.
Which device do you use rather than the tascam?

**Comment by onkelDead** [comment]
Hi,
sounds strange, that wire length have impact to reliability. Mine is around 1.5m.
Do you also transport audio via USB (recording)?

Since two years I use a Behringer X32.

Greets.

**Comment by MparkG** [comment]
Hola,
yes, audio playback and control over the usb port. its probably a 5m cable plus 1m extension.
it is whacky over that length.

alright, i see the appeal of a real mixing console over a soundcard and software controls.

kind regards

**Comment by onkelDead** [comment]
This issue is not related to the repository tascam-gtk. Closed.
