### ISSUE TITLE
Can't make it past ./configure

### ISSUE THREAD

**Issue by ZergeiW72** [onkelDead/tascam-gtk#19]
Hi ...

I'm stuck on this ...

./configure

configure: error: Package requirements (libxml++-2.6) were not met:

No package 'libxml++-2.6' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables XML2_CFLAGS
and XML2_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by Maxi98se** [comment]
Hi,
I have the same problem. Have you found a solution?

**Comment by es02** [comment]
Depending on what distro you use and its package naming conventions you probably want something named libxml++-devel

**Comment by onkelDead** [comment]
nowadays the configure is able to deal with multiple revisions of xml++
I'll close this issue here and advice you to reopen it, if the issue is still present.

**Comment by onkelDead** [comment]
closed by intention

**Comment by be1** [comment]
@ZergeiW72 and @Maxi98se  as say @es02 you have tin install libxml++ devel package with your distro's package manager. Which distro do you have ?
On Debian or Debian-related it's just a matter of: `sudo apt install libxml++2.6-dev`
On Arch or Arch-related, the package name is `libxml++2.6`
