### ISSUE TITLE
Moving Past libxml++-2.6

### ISSUE THREAD

**Issue by dhtseany** [onkelDead/tascam-gtk#24]
Hello,

This app is of vital importance to me as it's the only method of altering my Tascam 16x08's settings on my Linux systems, in my case Arch Linux.

libxml++-2.6 was released on May 5th 2004; it's hyper old at this point and requiring it for building and usage is preventing me from adjusting my Tascam on a fresh system. 

What, if any, are the plans for this app to get an overhaul to a more current version of libxml++ so it's lifespan can be extended? 

I'll contribute at least $100 if you're willing to put in the dev effort to start using the newer versions of libxml++ that are natively included in most modern distros, currently 3.2.4. Thanks!

**Comment by be1** [comment]
Hello @dhtseany 
Not sure, but I think libxml++2.6 to libxml++5.0 are API compatible to libxml++2.6. So this might be just a matter, for Arch, of modifying the `configure.ac` file to require the version that is on Arch. On Ubuntu kinetic, this seems to be transparent.
Maybe I'm wrong, but you can give a try on changing the **line 27** of `configure.ac`

**Comment by dhtseany** [comment]
@be1 Thanks for the tip! I've been playing with your suggestion for the last hour or so and while I'm able to clear the hurdle with ./configure I'm still not able to build because the version (2.6) seems to have been hard-coded into the app and in turn make isn't able to complete the make process. Any other advice for patching a fix to get it to not reference 2.6 would be appreciated.

**Comment by be1** [comment]
@dhtseany I have some spare time and I will install an Arch in a VM, then try to make it work...

**Comment by be1** [comment]
@dhtseany this was not very hard to patch. See https://github.com/be1/tascam-gtk/commit/5e1f1647563eb72f82566bb22c6e60b6bbecd051
Unlike Arch, several distributions seem to ship a modified version of libxml++2.6 instead of mutiple versioned libxml++.
So I would say it is not a good idea to submit my patch to @onkelDead repository as is, because it will fail to build on those distributions. The best would be to make configure script to allow choosing the libxml++ version to use, but I'm not used to autotools (autoconf / automake) and will have difficulties to achieve that.

**Comment by onkelDead** [comment]
@be1 I really appreciate your work, many thanx.

I've validated #25 and will apply it to the master.

Greets,
Detlef

**Comment by be1** [comment]
> @be1 I really appreciate your work, many thanx.
> 
> I've validated #25 and will apply it to the master.
> 
> Greets, Detlef

Thanks @onkelDead ! Your application is a must-have for us having a Tascam US-16x08, yet. Thanks to you!

**Comment by be1** [comment]
@dhtseany I think you can close the issue if you are satisfied, as the patches have now been merged upstream. Does it works for you? I also would be glad if you could contact me by email (it's shown on my profile page) to talk about the compensation you mentioned.

**Comment by dhtseany** [comment]
Thanks to @be1 for helping craft a good workaround solution for those of us with libxml++-3.0 or newer, I can confirm that your merged work does indeed build and run thus fixing our issues on Arch Linux.
