### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by tledford4** [onkelDead/tascam-gtk#28]
Many projects on github include build instructions in the README markdown file, list the sequence of terminal commands to use to build the project.

I've been unable to find such instructions for this project.

Could someone point me to them if I've over looked them, or provide them in a comment to this new "issue" I'm opening?

Thank you.

**Comment by mstrslv13** [comment]
You can follow the instructions [here,](https://interfacinglinux.com/2024/01/09/tascam-16x08/) which should work without hassle if you are using an up-to-date system. I just completed the installation in under 5 minutes on a fresh install of Zorin 17.1

Happy beat-making!

**Comment by tledford4** [comment]
Thank you!  It was the 'autoreconf' that I was missing.
