### ISSUE TITLE
Every control I touch gives error

### ISSUE THREAD

**Issue by lolgab** [onkelDead/tascam-gtk#3]
The GUI Works but nothing appens on the audio interface... Tried the driver on different kernel on Ubuntu 16.04. Linux-lowlatency-4.4.0  Linux-generic 4.8.6 
Alsamixer seem to see all the audio interface controls but from there I can't set the route values so I can't tell if it is a driver issue or a issue of the GTK app.

Thank you
Lorenzo
`
Control name='Level Meter',index=0 element not found
Control name='EQ High Volume',index=4 element not found
Control name='EQ High Volume',index=4 element not found
Control name='EQ High Volume',index=4 element not found
Control name='EQ High Volume',index=4 element not found
Control name='EQ High Frequence',index=4 element not found
Control name='EQ High Frequence',index=4 element not found
`

**Comment by onkelDead** [comment]
Hi, 
I'm currently working on a integration of the driver patch in the mainline kernel.
Thats why tascam-gtk and the kernel driver patch on github are out of synch.

I'll update the driver patch to the version just released in linux kernel 4.12 asap.

This will bring these components back to synch and they will work perfectly.

Greets
onkel

**Comment by lolgab** [comment]
So the patch is already included in the 4.12 kernel?

**Comment by onkelDead** [comment]
Yes, ist ist.Am 18.07.2017 5:55 nachm. schrieb lolgab <notifications@github.com>:So the patch is already included in the 4.12 kernel?

**Comment by lolgab** [comment]
Nice, I have it
