### ISSUE TITLE
Need help with basic firmware

### ISSUE THREAD

**Issue by brokentascam** [onkelDead/tascam-gtk#8]
Hello! 

I need help with my Tascam 16x08 and have searched relentlessly with little result. 
Finally I've found you - I'm hoping you'll be able to help me restore my firmware to factory settings. I was updating the standard firmware from tascam's website, and while the process was about 30% complete a notification popped up saying it was complete and to turn the device back on. It was still on at this point so I turned the Tascam off and back on again. 
At this point the orange USB light never came back on even when I tried plugging it into different devices (Mac and PC). I believe the original firmware has been corrupted. Since you're able to install your own firmware, perhaps you could assist me with regaining connection and installing software on the device again. 

My email is peytonknadler@gmail.com if you need to reach me directly.

Thank you!!

**Comment by onkelDead** [comment]
Hi,

sorry, but your assumption is wrong. 
I did not create or installed my own firmware on the Tascam device. My work pointed on a linux kernel extension to operate the device based on it's stock firmware. So I'm not able to help reset your device to original firmware.

But I wish you good luck to get help at other places.

Greets,
Onkel
